### ISSUE TITLE
markdown block

### ISSUE THREAD

**Issue by zz0-0** [zz0-0/dial_editor#37]
## Subtask for supporting markdown block

- [x] #38
- [x] https://github.com/zz0-0/dial_editor/issues/6
- [x] https://github.com/zz0-0/dial_editor/issues/9
- [ ] https://github.com/zz0-0/dial_editor/issues/8
- [x] #39
- [x] #40
